# Generated by Django 6.0.3 on 2026-05-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_first_name_customuser_google_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_login_google',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='registration_source',
        ),
        migrations.DeleteModel(
            name='ConfirmationCode',
        ),
    ]
